apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJtMzI0ZGVtb2FjcnFiYS5henVyZWNyLmlvIjp7InVzZXJuYW1lIjoibTMyNGRlbW9hY3JxYmEiLCJwYXNzd29yZCI6ImU3NU5Pbk9nYnVtb0x4emdOakRGZURmYmsvejh0RTdCV2ZPN1pyNjNHbitBQ1JBa2orY3ciLCJhdXRoIjoiYlRNeU5HUmxiVzloWTNKeFltRTZaVGMxVGs5dVQyZGlkVzF2VEhoNlowNXFSRVpsUkdaaWF5OTZPSFJGTjBKWFprODNXbkkyTTBkdUswRkRVa0ZyYWl0amR3PT0ifX19
kind: Secret
metadata:
  name: acr-pull
type: kubernetes.io/dockerconfigjson