name: CD
on: 
    push:
        branches: [main]
permissions:
  contents: write
env:
    ACR_LOGIN_SERVER: m324demoacrqba.azurecr.io

jobs:
    build-and-push-docker:
        runs-on: ubuntu-latest
        steps:
            - name: Compute image tag
              id: tag
              run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

            - name: Checkout code
              uses: actions/checkout@v4
              with:
                token: ${{ secrets.GITHUB_TOKEN }}

            - name: Login ACR
              uses: azure/docker-login@v2
              with:
                login-server: ${{ env.ACR_LOGIN_SERVER }}
                username: ${{ secrets.ACR_USERNAME }}
                password: ${{ secrets.ACR_PASSWORD }}

            - name: Build and tag docker image
              run: docker build -t ${{ env.ACR_LOGIN_SERVER }}/324_todo_nro:${{ steps.tag.outputs.TAG }}  -f dockerfile .
            
            - name: Push docker image to ACR
              run: docker push ${{ env.ACR_LOGIN_SERVER }}/324_todo_nro:${{ steps.tag.outputs.TAG }}
            
            - name: Update image tag with sed
              run: |
                FILE="k8s/deployment.yml"
                sed -i "s|image: m324demoacrqba.azurecr.io/324_todo_nro:.*|image: m324demoacrqba.azurecr.io/324_todo_nro:${{ steps.tag.outputs.TAG }}|" "$FILE"
                grep "image:" "$FILE"
            
            - name: Commit & push to main
              run: |
                git config user.name "github-actions[bot]"
                git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                git add k8s/deployment.yml
                git commit -m "Deploy: use image m324demoacrqba.azurecr.io/324_todo_nro:${{ steps.tag.outputs.TAG }} [skip ci]"
                git push origin HEAD:main
